kimai:
    user:
        registration: ENC[AES256_GCM,data:Dz8zgbU=,iv:5sfxGytW1jFS339pete/E2uwPtGg0LrFQKuBsu64LAo=,tag:mYaL3Lr7K/PfPLlV6jArbw==,type:bool]
        password_reset: ENC[AES256_GCM,data:dg0HU3w=,iv:X+TWQKslLejDC00By8g7mGob8ZF5w158Ao1EKx5LMoo=,tag:r1jTj1gt917LujiFLUn76A==,type:bool]
    defaults:
        user:
            theme: ENC[AES256_GCM,data:zyAUdA==,iv:A51wMeo1M+3TJR+SbCscQuUCoVaF+gVBOvjZgafEa4s=,tag:XResswAcZBPg7rxcsJfkIw==,type:str]
            language: ENC[AES256_GCM,data:/r0=,iv:+d2mwIo1nTJ7Ur30Phk8n2+6qnCMBmGWgtUZeLCrKM4=,tag:F4kB14Lo3M44lvrOW3v+5g==,type:str]
            timezone: ENC[AES256_GCM,data:03bOWu7M1MBXn2/KcA==,iv:ybYE3VYicH6MBjC9T3vPR32gkGBcoIyWA6MpsSgFJSQ=,tag:NK+3ixW/s0ohUnjmfq+hDw==,type:str]
            currency: ENC[AES256_GCM,data:9nWf,iv:RHn1CTV6qZsOpBaEpPRkWCgz3hBFCp74vew59t2XP44=,tag:N4VSJSYkK+lm6g+DhGEAhw==,type:str]
sops:
    age:
        - recipient: age1c9f7432jeskzm9xdu3pax4numqmeks5jnds8vddgxd0ytnemrpequ4s5zu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYktKRzRmMWQ0aWxBMWlx
            eXkwbVYwUUFocGhDSnNlTU1PZFRNQWFOSzNvCjdZRWFyYUhZblRlS1pCT3JoV3dv
            OXhBWTZOeTNVM0M4RXNuWWdxN2hRWmsKLS0tIHg5b0g5bzJIMGxYeUQ5TFRrMk5l
            VlBRZDdOQW85Y2dCSVpJUmNoakxlQTAKOVK0hsQDfAr70cX2isRs7Xo0QX72N5jG
            UOSPDtWSeQNabh/nflrFV317L2Xbk5NEdG2RCL2SjZ4dV7zI41QDjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1588vpcs2zagn3mhjrv97t6xvnzc4n7pfykulg4mcwe8h24dres5qq24usf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMmNDR25aUlZSd1ZIdDB1
            bUkwZjRBZHJ3aFAxcVdRb2NFcU5scVB2akVRCmNXUTdaZlhhOStqRTFNd0dGNGMw
            aEcrY2JMNHUvUDlnWnFjMDVhbDJpc0UKLS0tIGZzR1BMTThSRW5tdVRDYmlBb0Qw
            V0cyS3NES0FvTldQRnNkc3AzMjlFZkkKKDpKfHUqT5Can3Ai0TtW7dSORS1qBey1
            bwpcKu48Zx4mvZqPhKj2uqOSSSdybc8gJOFk2Eto6iuYmo4s5ii3AA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qgdfyx67sed3rnd2esq8rc534rsvzdcdunyg7ftr786z5jrltc2sxjtewt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTGF2U3dUbTFMMHRQbU5F
            UXhZQWV5WEdiNEZKOStxRVNKZVNPazI4WWlNCnpjSEtXMDNMZ0NNTGNOU0Foc3dW
            Ty9JVytDK25hV3JKdlJKRlRCbmFwWTQKLS0tIDQ0bkdBSWpJYVZMamN6L0YybWRB
            YmNmYWpoWU5VV2NtWkNLa3JYelNOdWMKf8yDbhMYbhWVi0SBVqV7iVuXpQMp5DWK
            hQUFiwz6Kbw36wal3w1J1wIBLj6RpFnS3uCLqrBny7NG2nPYcGNErw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-27T13:05:51Z"
    mac: ENC[AES256_GCM,data:Tt2TNzp+jEFNZ/wNWQBBAs7pCEDgoIoG1a6Z6U2I0214/M6s6wr2qHR03nGqepm6z/7KgKfmnn9XsdB4ATN3bhPp791soYMKsMhpEXD9WH1gu/xpyn3CM46GFeOdTMhkyRu6GIH7YG1zju4+quIYMBqiFVLBR39fX6UzWC3EV+s=,iv:tgaX9W98jLu8Kx16iaQYCvJO3e/jIKtppcD4lQPeZBk=,tag:goqMX/M8RTUBSo6BGF8ulg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
