# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2ce999f4-8edf-47bd-9e42-773a320bfb7c";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0197b04e-fea7-47dc-b5ed-f14d13a84206".device = "/dev/disk/by-uuid/0197b04e-fea7-47dc-b5ed-f14d13a84206";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C8A2-6080";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/mnt/ssd" = {
    device = "/dev/disk/by-uuid/2dc9266f-c7c9-4320-a9c5-2856cb9793b5";
    label = "ssd";
    fsType = "ext4";
    options = [
      "users" # Allow any user to mount and to unmount the filesystem
      "nofail" # Do not report errors for this device if it does not exist
      "x-gvfs-show" # Make mounted filesystem visible in file explorer
    ];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/5db59a5a-b4b7-4ef6-a96c-07ee1d8d4c60";
    label = "hdd";
    fsType = "ext4";
    options = [
      "users" # Allow any user to mount and to unmount the filesystem
      "nofail" # Do not report errors for this device if it does not exist
      "x-gvfs-show" # Make mounted filesystem visible in file explorer
    ];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f0u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
